#!/usr/bin/env bash

set -e
test -n "${PLAYENV_DEBUG}" && set -x

COMMAND="${1}"
if [ -z "${COMMAND}" ]; then
  playenv-help --usage completions >& 2
  exit 1
fi

COMMAND_PATH="$(command -v "playenv-${COMMAND}" || command -v "playenv-sh-${COMMAND}")"
if grep -iE "^([#%]|--|//) provide playenv completions" "${COMMAND_PATH}" > /dev/null; then
  shift
  exec "${COMMAND_PATH}" --complete "${@}"
fi

