#!/usr/bin/env bash
# Summary: Detect the file that sets the current playenv version

set -e
test -n "${PLAYENV_DEBUG}" && set -x

find_local_version_file() {
  local root="${1}"
  while [ -n "${root}" ]; do
    if [ -e "${root}/.play-version" ]; then
      echo "${root}/.play-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "${PLAYENV_DIR}"
[ "${PLAYENV_DIR}" = "${PWD}" ] || find_local_version_file "${PWD}"

global_version_file="${PLAYENV_ROOT}/version"

if [ -e "${global_version_file}" ]; then
  echo "${global_version_file}"
elif [ -e "${PLAYENV_ROOT}/global" ]; then
  echo "${PLAYENV_ROOT}/global"
elif [ -e "${PLAYENV_ROOT}/default" ]; then
  echo "${PLAYENV_ROOT}/default"
else
  echo "${global_version_file}"
fi

