#!/usr/bin/env bash
#
# Summary: Set or show the global Play Framework version
#
# Usage: playenv global <version>
#
# Sets the global Play Framework version. You can override the global
# version at any time by setting a directory-specific version with
# `playenv local` or by setting the `PLAYENV_VERSION` environment variable.
#
# <version> should be a string matching a Play Framework version known to
# playenv.
# The special version string `system` will use your default system
# Play Framework.
# Run `playenv versions` for a list of available Play Framework versions.

set -e
test -n "${PLAYENV_DEBUG}" && set -x

# Provide playenv completions
if [ "${1}" = "--complete" ]; then
  echo system
  exec playenv-versions --bare
fi

PLAYENV_VERSION="${1}"
PLAYENV_VERSION_FILE="${PLAYENV_ROOT}/version"

if [ -n "${PLAYENV_VERSION}" ]; then
  playenv-version-file-write "${PLAYENV_VERSION_FILE}" "${PLAYENV_VERSION}"
else
  playenv-version-file-read "${PLAYENV_VERSION_FILE}" ||
    playenv-version-file-read "${PLAYENV_ROOT}/global" ||
    playenv-version-file-read "${PLAYENV_ROOT}/default" ||
    echo system
fi

