#!/usr/bin/env bash
# Summary: List existing playenv shims
# Usage: playenv shims [--short]

set -e
test -n "${PLAYENV_DEBUG}" && set -x

# Provide playenv completions
if [ "${1}" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${PLAYENV_ROOT}/shims/"*; do
  if [ "${1}" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "${command}"
  fi
done | sort
