#!/usr/bin/env bash
# Summary: List all Play Framework versions that contain the given executable
# Usage: playenv whence [--path] <command>

set -e
test -n "${PLAYENV_DEBUG}" && set -x

# Provide playenv completions
if [ "${1}" = "--complete" ]; then
  echo --path
  exec playenv shims --short
fi

if [ "${1}" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="${1}"
  playenv-versions --bare | while read version; do
    path="$(playenv-prefix "${version}")/${command}"
    if [ -x "${path}" ]; then
      test "${print_paths}" && echo "${path}" || echo "${version}"
    fi
  done
}

PLAYENV_COMMAND="${1}"
if [ -z "${PLAYENV_COMMAND}" ]; then
  playenv-help --usage whence >& 2
  exit 1
fi

result="$(whence "${PLAYENV_COMMAND}")"
test -n "${result}" && echo "${result}"

