#!/usr/bin/env bash
# Summary: Show the current Play Framework version

set -e
test -n "${PLAYENV_DEBUG}" && set -x

if [ -z "${PLAYENV_VERSION}" ]; then
  PLAYENV_VERSION_FILE="$(playenv-version-file)"
  PLAYENV_VERSION="$(playenv-version-file-read "${PLAYENV_VERSION_FILE}" || true)"
fi

if [ -z "${PLAYENV_VERSION}" ] || [ "${PLAYENV_VERSION}" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="${1}"
  test -d "${PLAYENV_ROOT}/versions/${version}"
}

if version_exists "${PLAYENV_VERSION}"; then
  echo "${PLAYENV_VERSION}"
elif version_exists "${PLAYENV_VERSION#play-}"; then
  { echo "warning: ignoring extraneous \`play-\` prefix in version \`${PLAYENV_VERSION}\`"
    echo "         (set by $(playenv-version-origin))"
  } >& 2
  echo "${PLAYENV_VERSION#play-}"
else
  echo "playenv: version \`${PLAYENV_VERSION}\` is not installed" >& 2
  exit 1
fi

