#!/usr/bin/env bash
# Summary: Configure the shell environment for playenv

set -e
test -n "${PLAYENV_DEBUG}" && set -x

print=""
no_rehash=""
for args in "${@}"
do
  if [ "${args}" = "-" ]; then
    print=1
    shift
  fi
  if [ "${args}" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="${1}"
if [ -z "${shell}" ]; then
  shell="$(ps c -p "${PPID}" -o 'ucomm=' 2> /dev/null || true)"
  shell="${shell##-}"
  shell="${shell%% *}"
  shell="$(basename "${shell:-${SHELL}}")"
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "${READLINK}" ]; then
  echo "playenv: connot find readlink - are you missing GNU coreutils?" >& 2
  exit 1
fi

resolve_link() {
  ${READLINK} "${1}"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="${1}"

  while [ -n "${path}" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "${name}" || true)"
  done

  pwd
  cd "${cwd}"
}

root="$(abs_dirname "${0}")/.."

if [ -z "${print}" ]; then
  case "${shell}" in
    bash )
      profile='~/.bash_profile'
      ;;
    zsh )
      profile='~/.zshrc'
      ;;
    * )
      profile='your profile'
      ;;
  esac

  { echo "# Load playenv automatically by adding"
    echo "# the following to \"${profile}\":"
    echo ""
    case "${shell}" in
      * )
        echo 'eval "$(playenv init -)"'
        ;;
    esac
    echo ""
  } >& 2

  exit 1
fi

mkdir -p "${PLAYENV_ROOT}/"{shims,versions}

if [[ ":${PATH}:" != *:"${PLAYENV_ROOT}/shims":* ]]; then
  case "${shell}" in
    * )
      echo 'export PATH="'${PLAYENV_ROOT}'/shims:${PATH}"'
      ;;
  esac
fi

case "${shell}" in
  * )
    echo "export PLAYENV_SHELL=${shell}"
esac

completion="${root}/completions/playenv.${shell}"
if [ -r "${completion}" ]; then
  case "${shell}" in
    * ) echo "source '${completion}'" ;;
  esac
fi

if [ -z "${no_rehash}" ]; then
  echo 'playenv rehash 2> /dev/null'
fi

commands=(`playenv-commands --sh`)
case "${shell}" in
  * )
    cat <<EOS
 playenv() {
  local command
EOS
    ;;
esac

IFS="|"
cat <<EOS
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
    ${commands[*]})
      eval "\`playenv "sh-\$command" "\$@"\`";;
    * )
      command playenv "\$command" "\$@";;
  esac
}
EOS

