#!/usr/bin/env bash
set -e
test -n "${PLAYENV_DEBUG}" && set -x

# Provide playenv completions
if [ "${1}" = "--complete" ]; then
  exec playenv-rehash --complete
fi

shell="$(basename "${PLAYENV_SHELL:-${SHELL}}")"

# When playenv shell integration is enabled, delegate to playenv-rehash,
# then tell the shell to empty its command lookup cache.
playenv-rehash

case "${shell}" in
* )
  echo "hash -r 2> /dev/null || true"
  ;;
esac
