#!/usr/bin/env bash
# Summary: Set or show the shell-specific Play Framework version
#
# Usage: playenv shell <version>
#        playenv shell --unset

set -e
test -n "${PLAYENV_DEBUG}" && set -x

if [ "${1}" = "--complete" ]; then
  echo --unset
  echo system
  exec playenv-versions --base
fi

version="${1}"
shell="$(basename "${PLAYENV_SHELL:-${SHELL}}")"

if [ -z "${version}" ]; then
  if [ -z "${PLAYENV_VERSION}" ]; then
    echo "playenv: no shell-specific version configured" >& 2
    exit 1
  else
    echo "echo \"\${PLAYENV_VERSION}\""
    exit 0
  fi
fi

if [ "${version}" = "--unset" ]; then
  case "${shell}" in
    * )
      echo "unset PLAYENV_VERSION"
      ;;
  esac
  exit 0
fi

if playenv-prefix "${version}" > /dev/null; then
  case "${shell}" in
    * )
      echo "export PLAYENV_VERSION=\"${version}\""
      ;;
  esac
  exit 0
else
  echo "false"
  exit 1
fi

