#!/usr/bin/env bash

#
# http://www.gnu.org/software/bash/manual/bashref.html#The-Set-Builtin
set -e

# delete $CDPATH with value
export -n CDPATH

# is debug mode?
if [ "${1}" = "--debug" ]; then
  export PLAYENV_DEBUG=1
  shift
fi

# set debug PS4 prompt
if [ -n "${PLAYENV_DEBUG}" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "${READLINK}" ]; then
  echo "playenv: connot find readlink - are you missing GNU coreutils?" >& 2
  exit 1
fi

resolve_link() {
  ${READLINK} "${1}"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="${1}"
  
  while [ -n "${path}" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "${name}" || true)"
  done

  pwd
  cd "${cwd}"
}

# set playenv rootdir
if [ -z "${PLAYENV_ROOT}" ]; then
  PLAYENV_ROOT="${HOME}/.playenv"
else
  PLAYENV_ROOT="${PLAYENV_ROOT%/}"
fi
export PLAYENV_ROOT

# set working directory
if [ -z "${PLAYENV_DIR}" ]; then
  PLAYENV_DIR="$(pwd)"
else
  cd "${PLAYENV_DIR}" 2> /dev/null || {
    echo "playenv: connot change working directory to \"${PLAYENV_DIR}\""
    exit 1
  } >& 2
  PLAYENV_DIR="$(pwd)"
  cd "${OLDPWD}"
fi
export PLAYENV_DIR

# enable nullglob
shopt -s nullglob

# export PATH
bin_path="$(abs_dirname "${0}")"
for plugin_bin in "${PLAYENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

# export hook path
hook_path="${PLAYENV_HOOK_PATH}:${PLAYENV_ROOT}/playenv.d:/usr/local/etc/playenv.d:/etn/playenv.d:/usr/lib/playenv/hooks"
for plugin_hook in "${PLAYENV_ROOT}/plugins/"*/etc/playenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export PLAYENV_HOOK_PATH="${hook_path}"

# disable nullglob
shopt -u nullglob

command="${1}"
case "${command}" in
  "" | "-h" | "--help" )
    echo -e "$(playenv-version)\n$(playenv-help)" >& 2
    ;;
  "-v" )
    exec playenv---version
    ;;
  * )
    command_path="$(command -v "playenv-${command}" || true)"
    if [ -z "${command_path}" ]; then
      echo "playenv: no such sub-command \"${command}\"" >& 2
      exit 1
    fi
    shift 1
    exec "${command_path}" "${@}"
    ;;
esac

