#!/usr/bin/env bash
# Summary: Show the current Play Framework version and its origin
#
# Shows the currently selected Play Framework Version and how it was
# selected. To obtain only the version string, use `playenv
# version-name`.

set -e
test -n "${PLAYENV_DEBUG}" && set -x

echo "$(playenv-version-name) (set by $(playenv-version-origin))"

